tupla = (8, 15, 4, 39, 5, 89, 87, 19, 7, -755, 88, 123, 2, 11, 15, 9, 355)
print("#1. El último ítem de tupla")
print(tupla[-1])
print("2. El número de ítems de tupla")
print(len(tupla))
print("3. La posición donde se encuentra el ítem 87 de tupla")
print(tupla.index(87))
print("4. Una lista con los últimos tres ítems de tupla")
print(tupla[-3::])
print("5. Un ítem que haya en la posición 8 de tupla")
print(tupla[8])
print("6. El número de veces que el ítem 7 aparece en tupla")
print(tupla.count(7))